/* ===================================================================
   College Funding Command Center — scholarship dataset
   Research compiled June 2026 for the 2026–27 application cycle.
   Profile: NC Early College senior graduating spring 2027 WITH an
   Associate of Arts, transferring to a 4-year university (top choice
   Liberty University, VA) fall 2027. Fields: Film/Video, Spanish,
   Dietetics. No identifying student data is stored in this file.

   deadline.iso drives the urgency colour; deadline.label is shown.
   amountVal is a representative dollar figure used only for the
   "potential value" tally — verify real amounts on each site.
   =================================================================== */

window.PROFILE_LINE =
  "Transfer student · Associate's in hand · Fields: Film/Video · Spanish · Dietetics · Target: Liberty University (enroll Fall 2027) · 2026–27 cycle";

window.SCHOLARSHIPS = [

  /* ---------- FEDERAL & STATE AID ---------- */
  { id:"pell", name:"Federal Pell Grant", sponsor:"U.S. Dept. of Education", category:"Federal & State Aid",
    fields:["All"], amount:"Up to $7,395/yr", amountVal:7395,
    deadline:{label:"File FAFSA Oct 1, 2026", iso:"2026-10-01"}, priority:"urgent", portable:true,
    applyUrl:"https://studentaid.gov/h/apply-for-aid/fafsa",
    eligibility:"Need-based. Holding the A.A. does NOT end Pell eligibility — only a bachelor's does.",
    notes:"File the 2027–28 FAFSA the day it opens. Pell is the foundation that also unlocks Gilman and Gates.",
    flags:[] },
  { id:"fseog", name:"FSEOG (Supplemental Grant)", sponsor:"U.S. Dept. of Education", category:"Federal & State Aid",
    fields:["All"], amount:"$100–$4,000/yr", amountVal:4000,
    deadline:{label:"Via FAFSA — Oct 1, 2026", iso:"2026-10-01"}, priority:"high", portable:true,
    applyUrl:"https://studentaid.gov/understand-aid/types/grants/fseog",
    eligibility:"Lowest-SAI Pell recipients. Campus-based, first-come.",
    notes:"Limited pot at each school — filing FAFSA early is what wins this.", flags:["Funds run out; file FAFSA day one"] },
  { id:"teach", name:"TEACH Grant", sponsor:"U.S. Dept. of Education", category:"Federal & State Aid",
    fields:["Spanish"], amount:"Up to $3,772/yr", amountVal:3772,
    deadline:{label:"Via FAFSA", iso:""}, priority:"med", portable:true,
    applyUrl:"https://studentaid.gov/understand-aid/types/grants/teach",
    eligibility:"Becomes a loan unless you teach a high-need field 4 yrs. Spanish qualifies; Film/Dietetics do not.",
    notes:"Only worth it if she commits to teaching Spanish. Otherwise skip.", flags:["Converts to loan if service unmet"] },
  { id:"nc-grants", name:"NC State Grants (Next NC, Need-Based, Golden LEAF, Lottery)", sponsor:"State of North Carolina",
    category:"Federal & State Aid", fields:["All"], amount:"$3,000–$5,000+/yr", amountVal:0,
    deadline:{label:"NC schools only", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.cfnc.org/pay-for-college/",
    eligibility:"Restricted to NC's public/in-state institutions. Not usable in Virginia.",
    notes:"These DO NOT follow her to Liberty. Only relevant if she stays at an NC school. Kept here so the trade-off is visible.",
    flags:["NOT portable to Liberty / VA"] },

  /* ---------- LIBERTY INSTITUTIONAL ---------- */
  { id:"lu-academic", name:"Liberty Academic Scholarship (Transfer)", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$3,500–$6,500/yr", amountVal:3500,
    deadline:{label:"Rolling (at admission)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"With a conferred A.A., college GPA is used: 3.4–3.59→$3,500; 3.6–3.79→$4,000; 3.8–3.99→$5,600; 4.0→$6,500.",
    notes:"Her primary guaranteed merit award. NC residents pay the same tuition as Virginians.", flags:[] },
  { id:"lu-testbonus", name:"Liberty Test Score Bonus", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"+$1,000/yr → full tuition", amountVal:1000,
    deadline:{label:"Rolling (with test score)", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"Add-on: +$1,000/yr (SAT 1240+/ACT 26+); full tuition at SAT 1540+/ACT 35+.",
    notes:"Reason to sit the SAT/ACT even as a transfer — it stacks on the academic award.", flags:[] },
  { id:"lu-ptk", name:"Liberty Phi Theta Kappa Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000/yr × 4", amountVal:1000,
    deadline:{label:"At transfer", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"PTK member, 3.5+ college GPA, transferring directly from the inducting college.",
    notes:"Email proof to residentscholarships@liberty.edu. Stacks with the academic award — get PTK-inducted this fall.", flags:[] },
  { id:"lu-mas", name:"Liberty Middle America Scholarship", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"Up to $6,395/yr", amountVal:6395,
    deadline:{label:"Rolling (FAFSA-driven)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/middle-america-scholarship/",
    eligibility:"Need-based, families ~$35K–$95K income (SAI 1–17,000). Transfers qualify.",
    notes:"Stacks with Liberty aid up to the General Scholarship Rule cap.", flags:[] },
  { id:"lu-champion", name:"Liberty Champion Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000–$2,750/yr", amountVal:2750,
    deadline:{label:"Rolling (FAFSA-driven)", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/",
    eligibility:"Need-based by FAFSA Student Aid Index.", notes:"Part of the standard FAFSA-driven package.", flags:[] },
  { id:"lu-lbf", name:"Liberty LBF/LCN Church Scholarship", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000/yr × 4", amountVal:1000,
    deadline:{label:"Before matriculation", iso:""}, priority:"med", portable:false,
    applyUrl:"https://libertychurchnetwork.com/lu-scholarships/",
    eligibility:"Member of an LCN-affiliated church; pastor submits a letter on church letterhead.",
    notes:"Strong fit given church involvement — but check whether the family's church is LCN-affiliated. Doesn't stack with the VA Scholarship.",
    flags:["Confirm church is LCN-affiliated"] },
  { id:"lu-honors", name:"Liberty Honors Scholars Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$4,000/yr", amountVal:4000,
    deadline:{label:"With application", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/",
    eligibility:"3.5+ GPA and SAT 1330/ACT 28; must join the Honors program.", notes:"Test-score dependent.", flags:[] },
  { id:"lu-50k", name:"Liberty $50K Scholarship Giveaway", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"5 × $10,000", amountVal:10000,
    deadline:{label:"Enter by Mar 31, 2027", iso:"2027-03-31"}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/lp/50k-scholarship/",
    eligibility:"Sweepstakes-style entry; anyone interested in attending.", notes:"Low-effort entry, random draw.", flags:[] },
  { id:"lu-film-showcase", name:"Cinematic Arts Student Film Showcase", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["Film/Video"], amount:"$500 (×2/semester)", amountVal:500,
    deadline:{label:"Once enrolled", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/residential-at-liberty/bs-cinematic-arts/",
    eligibility:"Full-time residential undergrad; competitive film showcase.", notes:"A Liberty-era award once she's in the program.", flags:[] },

  /* ---------- MAJOR: FILM / VIDEO ---------- */
  { id:"bea", name:"BEA Scholarships (Orlik, Eaton, Fritts…)", sponsor:"Broadcast Education Association",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$1,000–$4,000", amountVal:4000,
    deadline:{label:"Oct 16, 2026", iso:"2026-10-16"}, priority:"high", portable:true,
    applyUrl:"https://beaweb.org/wp/scholarships/",
    eligibility:"Students at BEA member schools — Liberty IS a member, and 2-yr transfers to a BEA school are explicitly eligible.",
    notes:"The strongest, highest-certainty film fit. Create a BEA profile and apply once she commits to Liberty.", flags:[] },
  { id:"awm", name:"Alliance for Women in Media (NCTA / Ford)", sponsor:"AWM Foundation",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$5,000–$10,000", amountVal:10000,
    deadline:{label:"TBA — monitor (was closed mid-2026)", iso:""}, priority:"high", portable:true,
    applyUrl:"https://allwomeninmedia.org/foundation/scholarships/",
    eligibility:"Female media students; requires a video/multimedia project. Excellent woman+video fit.",
    notes:"Best field+amount fit but between cycles — join AWM student membership ($35) for alerts.", flags:["Watch for cycle reopening"] },
  { id:"princess-grace", name:"Princess Grace Award — Film", sponsor:"Princess Grace Foundation-USA",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$15,000", amountVal:15000,
    deadline:{label:"Nomination ~Feb 2, 2027", iso:"2027-02-02"}, priority:"med", portable:true,
    applyUrl:"https://pgfusa.org/apply/",
    eligibility:"Emerging film artists at nonprofit colleges; school must nominate. Very competitive.",
    notes:"A Liberty-era play once she has a faculty champion.", flags:["Requires school nomination"] },
  { id:"natas-region", name:"NATAS Regional Student Scholarship", sponsor:"Nat'l Academy of TV Arts & Sciences",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"~$1,500", amountVal:1500,
    deadline:{label:"~Spring 2027", iso:"2027-03-25"}, priority:"med", portable:true,
    applyUrl:"https://midsouthemmys.org/student-awards/",
    eligibility:"Students in first 3 years of college; some chapters are diversity-focused.",
    notes:"Confirm which chapter covers Ashe County (Nashville/Midsouth covers 'NC except Asheville' — likely hers).",
    flags:["Confirm regional chapter coverage"] },
  { id:"student-academy", name:"Student Academy Awards", sponsor:"Academy of Motion Picture Arts & Sciences",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$2,000–$5,000", amountVal:5000,
    deadline:{label:"~Apr 26, 2027", iso:"2027-04-26"}, priority:"med", portable:true,
    applyUrl:"https://www.oscars.org/saa",
    eligibility:"Post-secondary; a film made for coursework. HS students NOT eligible.", notes:"Free to enter; a Liberty-era, elite competition.", flags:[] },
  { id:"project-yellow-light", name:"Project Yellow Light", sponsor:"National Road Safety Foundation",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$2,000–$8,000", amountVal:8000,
    deadline:{label:"~Spring (annual)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.projectyellowlight.com",
    eligibility:"HS seniors + college students; make a safe-driving video PSA.", notes:"Pure video-skill scholarship, portable, legit warm-up entry.", flags:[] },
  { id:"cspan", name:"C-SPAN StudentCam", sponsor:"C-SPAN",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"$250–$5,000", amountVal:5000,
    deadline:{label:"~Jan 2027", iso:"2027-01-20"}, priority:"med", portable:true,
    applyUrl:"https://www.studentcam.org/",
    eligibility:"Documentary video on a set theme. Historically HS-focused.", notes:"Verify whether college/transfer students qualify this cycle.", flags:["Verify college eligibility"] },
  { id:"adobe-max", name:"Adobe MAX Creativity Awards (Young Creators)", sponsor:"Adobe",
    category:"Major: Film/Video", fields:["Film/Video"], amount:"Prizes / recognition", amountVal:0,
    deadline:{label:"~Jun–Jul (annual)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://max.adobe.com/creativity-awards/",
    eligibility:"Creators age 18–22; video/animation/photography.", notes:"Portfolio/resume booster in her medium — not tuition cash.", flags:[] },

  /* ---------- MAJOR: SPANISH ---------- */
  { id:"gilman", name:"Gilman International Scholarship", sponsor:"U.S. Dept. of State",
    category:"Major: Spanish", fields:["Spanish"], amount:"Up to $5,000 (+$3,000 language)", amountVal:8000,
    deadline:{label:"~Mar 2027 (study-abroad term)", iso:"2027-03-05"}, priority:"high", portable:true,
    applyUrl:"https://www.gilmanscholarship.org/applicants/eligibility/",
    eligibility:"Must be a Pell recipient, undergrad, doing credit-bearing study abroad. Spanish + abroad = ideal.",
    notes:"The best portable Spanish award IF she gets Pell. Tied to a study-abroad term.", flags:["Requires Pell eligibility"] },
  { id:"sigma-delta-pi", name:"Sigma Delta Pi Study Abroad Award", sponsor:"Sigma Delta Pi (Spanish Honor Society)",
    category:"Major: Spanish", fields:["Spanish"], amount:"$2,500 (up to 10)", amountVal:2500,
    deadline:{label:"Junior year+ (enrollment fixed Feb 1)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://sigmadeltapi.org/blog/awards/undergraduate-study-abroad-awards/",
    eligibility:"Spanish major/minor, junior standing, active member, 12+ Spanish hrs, adviser nomination.",
    notes:"Confirm Liberty has a chapter; not winnable until junior year.", flags:["Confirm Liberty chapter"] },
  { id:"nse-senior", name:"NSE Senior Scholarship", sponsor:"AATSP / National Spanish Exam",
    category:"Major: Spanish", fields:["Spanish"], amount:"$1,000", amountVal:1000,
    deadline:{label:"~May 2027", iso:"2027-05-03"}, priority:"med", portable:true,
    applyUrl:"https://nationalspanishexam.org/awards/students/senior-scholarship/",
    eligibility:"Graduating seniors who earned National Spanish Exam medals in 2024 AND 2025.",
    notes:"Only works if she has the prior exam medals — verify with her Spanish teacher.", flags:["Requires prior NSE medals"] },
  { id:"boren", name:"Boren Scholarship", sponsor:"National Security Education Program",
    category:"Major: Spanish", fields:["Spanish"], amount:"Up to $25,000", amountVal:25000,
    deadline:{label:"~Jan 28, 2027", iso:"2027-01-28"}, priority:"med", portable:true,
    applyUrl:"https://www.borenawards.org/apply-now",
    eligibility:"Less-commonly-taught languages in critical regions; excludes Western Europe; 1-yr federal-service obligation.",
    notes:"Weak fit for Spanish — listed for completeness.", flags:["Spanish not prioritized; service obligation"] },

  /* ---------- MAJOR: DIETETICS ---------- */
  { id:"and-foundation", name:"AND Foundation Undergrad Scholarships", sponsor:"Academy of Nutrition & Dietetics Foundation",
    category:"Major: Dietetics", fields:["Dietetics"], amount:"$500–$25,000", amountVal:2500,
    deadline:{label:"Feb 10 – Apr 2, 2027", iso:"2027-04-02"}, priority:"med", portable:true,
    applyUrl:"https://www.eatrightfoundation.org/apply-for-funding/scholarships",
    eligibility:"Requires enrollment in an ACEND-accredited program (DPD/Coordinated/FEM).",
    notes:"250+ awards via one app — BUT Liberty's nutrition degree is CEPH (public health), not ACEND, so she'd be INELIGIBLE at Liberty.",
    flags:["Liberty is NOT ACEND-accredited — see dietetics decision"] },
  { id:"nsca", name:"NSCA Foundation Scholarships", sponsor:"NSCA Foundation",
    category:"Major: Dietetics", fields:["Dietetics"], amount:"$1,500–$2,000+", amountVal:2000,
    deadline:{label:"Aug 1 – Oct 15, 2026", iso:"2026-10-15"}, priority:"med", portable:true,
    applyUrl:"https://www.nsca.com/about-us/nsca-foundation/scholarships/",
    eligibility:"Strength-&-conditioning / exercise-science field; NSCA membership required.",
    notes:"Fits if her path reads as exercise/sport science rather than pure nutrition.", flags:["Requires NSCA membership"] },
  { id:"snf", name:"School Nutrition Foundation (Schwan's)", sponsor:"School Nutrition Association",
    category:"Major: Dietetics", fields:["Dietetics"], amount:"$2,500", amountVal:2500,
    deadline:{label:"~Mar 2027", iso:"2027-03-13"}, priority:"med", portable:true,
    applyUrl:"https://schoolnutrition.org/snf/scholarships",
    eligibility:"SNA member ≥1 yr + school-food-service work history.", notes:"Unlikely unless she works in school nutrition.", flags:["Requires SNA membership + work history"] },
  { id:"vand", name:"Virginia Academy of Nutrition & Dietetics", sponsor:"VAND",
    category:"Major: Dietetics", fields:["Dietetics"], amount:"~$1,000", amountVal:1000,
    deadline:{label:"Varies", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.eatrightvirginia.org/awards-and-scholarship",
    eligibility:"VAND member; the confirmed $1,000 award is graduate-level.", notes:"Join as a student if she attends Liberty; verify an undergrad award exists.", flags:[] },

  /* ---------- TRANSFER FLAGSHIP ---------- */
  { id:"jkc-college", name:"Jack Kent Cooke — College Scholarship", sponsor:"Jack Kent Cooke Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Up to $55,000/yr", amountVal:55000,
    deadline:{label:"Aug 19 – Nov 11, 2026", iso:"2026-11-11"}, priority:"urgent", portable:true,
    applyUrl:"https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    eligibility:"HS seniors, AGI ≤ $95K. Needs 3.75 UNWEIGHTED GPA — likely above her 3.5+.",
    notes:"Her STATUS fits this one, but the 3.75 GPA bar is the obstacle. Can't hold both JKC awards.", flags:["3.75 unweighted GPA required"] },
  { id:"jkc-transfer", name:"Jack Kent Cooke — Undergraduate Transfer Scholarship", sponsor:"Jack Kent Cooke Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Up to $55,000/yr", amountVal:55000,
    deadline:{label:"Aug 19 – Dec 9, 2026", iso:"2026-12-09"}, priority:"urgent", portable:true,
    applyUrl:"https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship/",
    eligibility:"Community-college students transferring to a bachelor's; 3.5 GPA, AGI ≤ $95K. Her GPA fits.",
    notes:"Highest-value target. Her dual HS-senior/CC status is a gray zone — email scholarships@jkcf.org NOW to confirm eligibility in writing.",
    flags:["Email JKC to confirm dual-enrollment eligibility"] },
  { id:"gates", name:"The Gates Scholarship", sponsor:"Gates Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Full cost of attendance (~$160k)", amountVal:40000,
    deadline:{label:"Sept 15, 2026", iso:"2026-09-15"}, priority:"urgent", portable:true,
    applyUrl:"https://www.thegatesscholarship.org/scholarship/",
    eligibility:"HS senior, Pell-eligible, GPA 3.3+, AND a member of a listed minority group.",
    notes:"Last-dollar, full-ride. Two hard gates: Pell-eligibility and ethnicity criteria — confirm both before investing time.",
    flags:["Requires Pell-eligibility + listed ethnicity"] },
  { id:"coca-cola-scholars", name:"Coca-Cola Scholars Program", sponsor:"Coca-Cola Scholars Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"$20,000", amountVal:20000,
    deadline:{label:"Opens Aug 3 · due Sept 30, 2026", iso:"2026-09-30"}, priority:"urgent", portable:true,
    applyUrl:"https://www.coca-colascholarsfoundation.org/apply/",
    eligibility:"HS senior graduating 2026–27, 3.0+ GPA. Her early-college status does NOT disqualify her.",
    notes:"150 scholars/yr — very competitive but a clean eligibility fit.", flags:[] },
  { id:"ptk-allusa", name:"PTK All-USA / Coca-Cola Academic Team / New Century", sponsor:"Phi Theta Kappa",
    category:"Transfer Flagship", fields:["All"], amount:"$1,300–$3,000", amountVal:3000,
    deadline:{label:"Jul – Dec 2026", iso:"2026-12-01"}, priority:"urgent", portable:true,
    applyUrl:"https://www.ptk.org/scholarships/apply-now/",
    eligibility:"PTK member; college nominates for the All-USA Academic Team (feeds all three).",
    notes:"TIMING TRAP: must apply while still dual-enrolled (HS+CC), before she graduates HS spring 2027. After graduation she's locked out.",
    flags:["Apply before HS graduation — dual-enrollment only"] },
  { id:"ptk-membership", name:"Phi Theta Kappa Membership (enabler)", sponsor:"Phi Theta Kappa",
    category:"Transfer Flagship", fields:["All"], amount:"~$65–90 (one-time fee)", amountVal:0,
    deadline:{label:"Fall 2026 (get inducted)", iso:"2026-11-01"}, priority:"high", portable:true,
    applyUrl:"https://www.ptk.org/scholarships/faqs/",
    eligibility:"Early-college students with 12+ credits & 3.5 GPA are eligible — confirm her CC has a chapter.",
    notes:"This is the KEY that unlocks the Liberty PTK award + Coca-Cola Academic Team + transfer scholarships. Ask her CC's PTK advisor.",
    flags:["Confirm CC has an active PTK chapter"] },

  /* ---------- HONOR SOCIETIES ---------- */
  { id:"beta", name:"National Beta Scholarship", sponsor:"National Beta Club",
    category:"Honor Society", fields:["All"], amount:"$1,000–$20,000", amountVal:20000,
    deadline:{label:"Opens ~Nov 2026 · due ~Jan 15, 2027", iso:"2027-01-15"}, priority:"urgent", portable:true,
    applyUrl:"https://www.betaclub.org/scholarship-2/",
    eligibility:"Active 12th-grade Senior Beta Member. She IS a Beta member.",
    notes:"SENIOR-YEAR-ONLY — this fall/winter is her one and only window, ever. 260 awards. Apply at scholarship.betaclub.org.",
    flags:["Senior-year-only — no second chance after graduation"] },
  { id:"nhs", name:"NHS Scholarship", sponsor:"National Honor Society (NASSP)",
    category:"Honor Society", fields:["All"], amount:"$3,200–$25,000", amountVal:25000,
    deadline:{label:"Opens Sept 3 · due Nov 20, 2026", iso:"2026-11-20"}, priority:"high", portable:true,
    applyUrl:"https://www.nationalhonorsociety.org/the-nhs-scholarship/",
    eligibility:"Active NHS member (SEPARATE from Beta Club) verified by chapter adviser.",
    notes:"Worth more than Beta but only if she's an NHS member too — confirm. Earlier deadline than Beta.",
    flags:["Requires NHS membership (not the same as Beta)"] },
  { id:"mu-alpha-theta", name:"Mu Alpha Theta Scholarship", sponsor:"Mu Alpha Theta",
    category:"Honor Society", fields:["All"], amount:"$4,000–$5,000", amountVal:4000,
    deadline:{label:"~Spring 2027", iso:""}, priority:"med", portable:true,
    applyUrl:"https://mualphatheta.org/scholarships",
    eligibility:"Active member of a math-honor chapter; chapter-nominated (max 2 per chapter).",
    notes:"Only if her Early College has a chapter and she's nominated. A Two-Year College award also exists.", flags:["Chapter-nominated only"] },

  /* ---------- HERITAGE (DAR / SAR) ---------- */
  { id:"dar-dunn", name:"DAR Lillian & Arthur Dunn Scholarship", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"$2,500/yr × 4", amountVal:2500,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"high", portable:true,
    applyUrl:"https://dar.academicworks.com/",
    eligibility:"Child of a CURRENT dues-paying DAR member. Both she AND her mother are DAR members — this is the rare fit.",
    notes:"The one DAR award needing a parent member. Have her mother's National Number ready; confirm mom's dues are active. 1,000-word essay.",
    flags:["Confirm mother's DAR dues are current"] },
  { id:"dar-general", name:"DAR National Application (general awards)", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"$2,000–$5,000", amountVal:5000,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"med", portable:true,
    applyUrl:"https://dar.academicworks.com/",
    eligibility:"One online app covers many awards (Thomas, music, America 250!, etc.).",
    notes:"Apply to every award she qualifies for — but DAR gives only ONE award per cycle.", flags:["One DAR award per cycle"] },
  { id:"dar-otpt", name:"DAR Occupational/Physical Therapy Scholarship", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["Dietetics"], amount:"$5,000", amountVal:5000,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"med", portable:true,
    applyUrl:"https://dar.academicworks.com/opportunities/1019",
    eligibility:"OT/PT/art/music therapy students with financial need.", notes:"Relevant only if she pivots toward a therapy/health field.", flags:[] },
  { id:"sar-knight", name:"SAR George S. & Stella M. Knight Essay Contest", sponsor:"Sons of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"1st $6,000", amountVal:6000,
    deadline:{label:"~Dec 31, 2026", iso:"2026-12-31"}, priority:"high", portable:true,
    applyUrl:"https://www.sar.org/george-s-stella-m-knight-essay-contest/",
    eligibility:"Any HS student (grades 9–12); 800–1,200 word essay on the Revolution. No ancestry/membership needed.",
    notes:"Open to her now; enter via the local NC SAR chapter. A contest win — stacks independently of need-based aid.", flags:[] },
  { id:"sar-rumbaugh", name:"SAR Rumbaugh Historical Oration Contest", sponsor:"Sons of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"1st $8,000", amountVal:8000,
    deadline:{label:"Local/state vary (fall–winter)", iso:""}, priority:"high", portable:true,
    applyUrl:"https://www.sar.org/joseph-s-rumbaugh-historical-oration-contest/",
    eligibility:"Any student grades 9–12; 5–6 min memorized oration on the Revolution.",
    notes:"Open to her now; contact the local NC SAR chapter for local/state deadlines.", flags:[] },

  /* ---------- FAITH-BASED ---------- */
  { id:"provision-bullard", name:"Bullard Family Scholarship (ministry)", sponsor:"NC Baptist Foundation / Provision",
    category:"Faith-Based", fields:["All"], amount:"$500–$2,500/yr", amountVal:2500,
    deadline:{label:"~May 1, 2027 (opens Jan 1)", iso:"2027-05-01"}, priority:"high", portable:true,
    applyUrl:"https://www.provision.org/scholarships",
    eligibility:"NC resident, member of a Baptist State Convention of NC church, committed to full-time Christian ministry.",
    notes:"Strongest fit if heading into ministry. Only ONE Provision award per cycle — pick the best-fit one.", flags:["One Provision award per cycle"] },
  { id:"provision-general", name:"Martha Watson / Nell J. Clary Scholarship", sponsor:"NC Baptist Foundation / Provision",
    category:"Faith-Based", fields:["All"], amount:"$500–$2,500/yr", amountVal:2500,
    deadline:{label:"~May 1, 2027", iso:"2027-05-01"}, priority:"med", portable:true,
    applyUrl:"https://www.provision.org/scholarships",
    eligibility:"NC resident, BSCNC church member; general (non-ministry) students. Fits 3.5 GPA + church leadership.",
    notes:"The general alternative to Bullard — but only one Provision award per cycle.", flags:["One Provision award per cycle"] },
  { id:"christian-connector", name:"Christian Connector Scholarship Drawings", sponsor:"The Christian Connector",
    category:"Faith-Based", fields:["All"], amount:"$2,000–$5,000", amountVal:5000,
    deadline:{label:"Annual — watch for reopen", iso:""}, priority:"med", portable:true,
    applyUrl:"http://christianconnector.com/",
    eligibility:"No-essay drawing; enrolling at a Christ-centered college.", notes:"May 2026 cycle closed — monitor. Verify the 'first-time full-time' rule doesn't exclude a transfer.", flags:["Verify transfer eligibility"] },
  { id:"bold-christian", name:"Bold.org Christian Colleges No-Essay", sponsor:"Bold.org",
    category:"Faith-Based", fields:["All"], amount:"Varies", amountVal:1000,
    deadline:{label:"Rolling (monthly)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://bold.org/scholarships/christian-colleges-no-essay-scholarship/",
    eligibility:"Any student attending a Christian college.", notes:"Easy entry; browse Bold.org's full Christian list for more.", flags:[] },
  { id:"fca", name:"FCA Scholarships", sponsor:"Fellowship of Christian Athletes",
    category:"Faith-Based", fields:["All"], amount:"Varies", amountVal:1000,
    deadline:{label:"~May (varies by chapter)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.carolinasfca.org/",
    eligibility:"Active FCA huddle member; decentralized by chapter.", notes:"Ask the Carolinas/NC FCA rep about college awards.", flags:["Requires active FCA involvement"] },

  /* ---------- CIVIC & LOCAL ---------- */
  { id:"elks-mvs", name:"Elks Most Valuable Student", sponsor:"Elks National Foundation",
    category:"Civic & Local", fields:["All"], amount:"$1,000–$12,500/yr (top $30k)", amountVal:12500,
    deadline:{label:"Aug 1 – Nov 12, 2026", iso:"2026-11-12"}, priority:"urgent", portable:true,
    applyUrl:"https://www.elks.org/scholars/scholarships/mvs.cfm",
    eligibility:"HS seniors (not grads), US citizens; judged on scholarship, leadership, financial need. No Elks relation needed.",
    notes:"High-value, portable, and a clean senior-year fit. 500 awards nationally.", flags:[] },
  { id:"local-foundation", name:"Ashe County / NC Community Foundation Scholarships", sponsor:"NC Community Foundation & local funds",
    category:"Civic & Local", fields:["All"], amount:"Varies (often $500–$5,000)", amountVal:3000,
    deadline:{label:"~Spring 2027", iso:"2027-03-01"}, priority:"high", portable:true,
    applyUrl:"https://www.nccommunityfoundation.org/students",
    eligibility:"Local/regional scholarships for Ashe County students — usually portable, high hit-rate.",
    notes:"Highest-ROI per effort. Check the local community foundation AND her high-school guidance office for the local list.",
    flags:["Pull the local list from her guidance counselor"] },
  { id:"prudential", name:"Prudential Emerging Visionaries", sponsor:"Prudential",
    category:"Civic & Local", fields:["All"], amount:"$5,000–$15,000", amountVal:15000,
    deadline:{label:"~Nov 2026", iso:"2026-11-04"}, priority:"med", portable:true,
    applyUrl:"https://www.prudential.com/links/about/corporate-social-responsibility/emerging-visionaries",
    eligibility:"Ages 14–18; a community-service or financial-solution project.", notes:"Formerly Spirit of Community — fits her church/civic leadership.", flags:[] },
  { id:"dr-pepper", name:"Dr Pepper Tuition Giveaway", sponsor:"Keurig Dr Pepper",
    category:"Civic & Local", fields:["Film/Video"], amount:"Up to $100,000", amountVal:100000,
    deadline:{label:"Opens ~Aug · due Sept 30, 2026", iso:"2026-09-30"}, priority:"med", portable:true,
    applyUrl:"https://www.drpepper.com/tuition/",
    eligibility:"Ages 18–24; a 60-second video on your goals. Transfer-friendly (age-based, not freshman-only).",
    notes:"Plays to her video skills. Big upside, low barrier to enter.", flags:[] },
  { id:"american-legion", name:"American Legion / Auxiliary Scholarships", sponsor:"American Legion (NC Dept.)",
    category:"Civic & Local", fields:["All"], amount:"Varies", amountVal:2000,
    deadline:{label:"~Spring 2027", iso:"2027-03-01"}, priority:"med", portable:true,
    applyUrl:"https://www.legion.org/scholarships",
    eligibility:"Several awards; some favor descendants of veterans.", notes:"Check the NC Department's specific awards and deadlines.", flags:[] },
  { id:"dollars-for-scholars", name:"Dollars for Scholars (local chapter)", sponsor:"Scholarship America",
    category:"Civic & Local", fields:["All"], amount:"Varies", amountVal:1000,
    deadline:{label:"~Spring 2027", iso:"2027-03-15"}, priority:"med", portable:true,
    applyUrl:"https://scholarshipamerica.org/students/browse-scholarships/",
    eligibility:"Local-chapter scholarships, usually portable.", notes:"See whether Ashe County has an active chapter.", flags:[] }

];
