/* ===================================================================
   College Funding Command Center — scholarship dataset
   Research compiled June–Aug 2026 for the 2026–27 application cycle.

   PROFILE: NC Early College senior graduating spring 2027 WITH an
   Associate of Arts, enrolling at a 4-year university FALL 2027.
   MAJOR: UNDECIDED. Top choice Liberty University (VA); NC schools
   also under active consideration. No identifying data stored here.

   TWO ELIGIBILITY LANES (important):
   • As a graduating HIGH-SCHOOL SENIOR she qualifies for senior-year
     national awards (Coca-Cola, Gates, Dell, Elks, DAR, etc.).
   • As a college entrant holding an ASSOCIATE'S (~60 cr, junior
     standing) she is a TRANSFER for university admission — so the
     famous NC full-ride freshman scholarships are CLOSED to her.
   Cards note which lane applies.

   portable === false  → NC-only or school-specific (won't follow her
   to Liberty). amountVal is a representative figure for the tally.
   =================================================================== */

window.PROFILE_LINE =
  "Undecided major · Varsity swimmer · Transfer w/ associate's · Liberty #1 + NC schools in play · 2026–27 · Goal: tuition-free";

window.SCHOLARSHIPS = [

  /* ---------- FEDERAL AID ---------- */
  { id:"pell", name:"Federal Pell Grant", sponsor:"U.S. Dept. of Education", category:"Federal Aid",
    fields:["All"], amount:"Up to $7,395/yr", amountVal:7395,
    deadline:{label:"File FAFSA Oct 1, 2026", iso:"2026-10-01"}, priority:"urgent", portable:true,
    applyUrl:"https://studentaid.gov/h/apply-for-aid/fafsa",
    eligibility:"Need-based. Holding the A.A. does NOT end Pell eligibility — only a bachelor's does.",
    notes:"The foundation of the whole plan. Filing FAFSA also unlocks FSEOG, Gates, Golden LEAF, and Next NC.", flags:[] },
  { id:"fseog", name:"FSEOG (Supplemental Grant)", sponsor:"U.S. Dept. of Education", category:"Federal Aid",
    fields:["All"], amount:"$100–$4,000/yr", amountVal:4000,
    deadline:{label:"Via FAFSA — Oct 1, 2026", iso:"2026-10-01"}, priority:"high", portable:true,
    applyUrl:"https://studentaid.gov/understand-aid/types/grants/fseog",
    eligibility:"Lowest-SAI Pell recipients. Campus-based, first-come.",
    notes:"Limited pot per school — file FAFSA the day it opens.", flags:["Funds run out; file early"] },
  { id:"teach", name:"TEACH Grant", sponsor:"U.S. Dept. of Education", category:"Federal Aid",
    fields:["All"], amount:"Up to $3,772/yr", amountVal:3772,
    deadline:{label:"Via FAFSA", iso:""}, priority:"med", portable:true,
    applyUrl:"https://studentaid.gov/understand-aid/types/grants/teach",
    eligibility:"Only if she later chooses to teach a high-need field 4 yrs. Becomes a loan otherwise.",
    notes:"Park here for now — relevant only if a teaching path emerges once the major is decided.", flags:["Converts to loan if service unmet"] },

  /* ---------- LIBERTY INSTITUTIONAL ---------- */
  { id:"lu-academic", name:"Liberty Academic Scholarship (Transfer)", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$3,500–$6,500/yr", amountVal:3500,
    deadline:{label:"Rolling (at admission)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"With a conferred A.A., college GPA sets the tier: 3.4–3.59→$3,500 … 4.0→$6,500.",
    notes:"Her primary guaranteed merit award. NC residents pay the same tuition as Virginians.", flags:[] },
  { id:"lu-testbonus", name:"Liberty Test Score Bonus", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"+$1,000/yr → full tuition", amountVal:1000,
    deadline:{label:"Rolling (with test score)", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"+$1,000/yr at SAT 1240+/ACT 26+; full tuition at SAT 1540+/ACT 35+.",
    notes:"A reason to sit the SAT/ACT even as a transfer — it stacks on the academic award.", flags:[] },
  { id:"lu-ptk", name:"Liberty Phi Theta Kappa Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000/yr × 4", amountVal:1000,
    deadline:{label:"At transfer", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/residential/undergraduate/transfer-students/transfer-student-scholarships/",
    eligibility:"PTK member, 3.5+ college GPA, transferring directly from the inducting college.",
    notes:"Email proof to residentscholarships@liberty.edu. Get PTK-inducted this fall to unlock it.", flags:[] },
  { id:"lu-mas", name:"Liberty Middle America Scholarship", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"Up to $6,395/yr", amountVal:6395,
    deadline:{label:"Rolling (FAFSA-driven)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/middle-america-scholarship/",
    eligibility:"Need-based, families ~$35K–$95K income (SAI 1–17,000). Transfers qualify.",
    notes:"Stacks with Liberty aid up to the General Scholarship Rule cap.", flags:[] },
  { id:"lu-champion", name:"Liberty Champion Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000–$2,750/yr", amountVal:2750,
    deadline:{label:"Rolling (FAFSA-driven)", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/",
    eligibility:"Need-based by FAFSA Student Aid Index.", notes:"Part of the standard FAFSA-driven package.", flags:[] },
  { id:"lu-lbf", name:"Liberty LBF/LCN Church Scholarship", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$1,000/yr × 4", amountVal:1000,
    deadline:{label:"Before matriculation", iso:""}, priority:"med", portable:false,
    applyUrl:"https://libertychurchnetwork.com/lu-scholarships/",
    eligibility:"Member of an LCN-affiliated church; pastor submits a letter on church letterhead.",
    notes:"Strong fit given church involvement — check whether the family's church is LCN-affiliated.",
    flags:["Confirm church is LCN-affiliated"] },
  { id:"lu-honors", name:"Liberty Honors Scholars Award", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"$4,000/yr", amountVal:4000,
    deadline:{label:"With application", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/student-financial-services/scholarships/",
    eligibility:"3.5+ GPA and SAT 1330/ACT 28; must join the Honors program.", notes:"Test-score dependent.", flags:[] },
  { id:"lu-50k", name:"Liberty $50K Scholarship Giveaway", sponsor:"Liberty University",
    category:"Liberty Institutional", fields:["All"], amount:"5 × $10,000", amountVal:10000,
    deadline:{label:"Enter by Mar 31, 2027", iso:"2027-03-31"}, priority:"med", portable:false,
    applyUrl:"https://www.liberty.edu/lp/50k-scholarship/",
    eligibility:"Sweepstakes-style entry; anyone interested in attending.", notes:"Low-effort entry, random draw.", flags:[] },

  /* ---------- TRANSFER FLAGSHIP (national, high-value) ---------- */
  { id:"jkc-transfer", name:"Jack Kent Cooke — Undergraduate Transfer Scholarship", sponsor:"Jack Kent Cooke Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Up to $55,000/yr", amountVal:55000,
    deadline:{label:"Aug 19 – Dec 9, 2026", iso:"2026-12-09"}, priority:"urgent", portable:true,
    applyUrl:"https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship/",
    eligibility:"Community-college students transferring to a bachelor's; 3.5 GPA, AGI ≤ $95K. Any major.",
    notes:"Highest-value target. Her dual HS/CC status is a gray zone — email scholarships@jkcf.org NOW to confirm in writing.",
    flags:["Email JKC to confirm dual-enrollment eligibility"] },
  { id:"jkc-college", name:"Jack Kent Cooke — College Scholarship", sponsor:"Jack Kent Cooke Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Up to $55,000/yr", amountVal:55000,
    deadline:{label:"Aug 19 – Nov 11, 2026", iso:"2026-11-11"}, priority:"high", portable:true,
    applyUrl:"https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    eligibility:"HS seniors, AGI ≤ $95K. Needs 3.75 UNWEIGHTED GPA — likely above her 3.5+.",
    notes:"Her status fits, but the 3.75 GPA bar is the obstacle. Can't hold both JKC awards.", flags:["3.75 unweighted GPA required"] },
  { id:"gates", name:"The Gates Scholarship", sponsor:"Gates Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"Full cost of attendance (~$160k)", amountVal:40000,
    deadline:{label:"Sept 15, 2026", iso:"2026-09-15"}, priority:"urgent", portable:true,
    applyUrl:"https://www.thegatesscholarship.org/scholarship/",
    eligibility:"HS senior, Pell-eligible, GPA 3.3+, AND a member of a listed minority group.",
    notes:"Last-dollar full ride. Two hard gates: Pell-eligibility and ethnicity — confirm both first.",
    flags:["Requires Pell-eligibility + listed ethnicity"] },
  { id:"coca-cola-scholars", name:"Coca-Cola Scholars Program", sponsor:"Coca-Cola Scholars Foundation",
    category:"Transfer Flagship", fields:["All"], amount:"$20,000", amountVal:20000,
    deadline:{label:"Opens Aug 3 · due Sept 30, 2026", iso:"2026-09-30"}, priority:"urgent", portable:true,
    applyUrl:"https://www.coca-colascholarsfoundation.org/apply/",
    eligibility:"HS senior graduating 2026–27, 3.0+ GPA, any major. Early-college status does NOT disqualify her.",
    notes:"150 scholars/yr — very competitive but a clean eligibility fit and an early deadline.", flags:[] },
  { id:"ptk-allusa", name:"PTK All-USA / Coca-Cola Academic Team / New Century", sponsor:"Phi Theta Kappa",
    category:"Transfer Flagship", fields:["All"], amount:"$1,300–$3,000", amountVal:3000,
    deadline:{label:"Jul – Dec 2026", iso:"2026-12-01"}, priority:"urgent", portable:true,
    applyUrl:"https://www.ptk.org/scholarships/apply-now/",
    eligibility:"PTK member; college nominates for the All-USA Academic Team (feeds all three).",
    notes:"TIMING TRAP: must apply while still dual-enrolled, before spring-2027 HS graduation.",
    flags:["Apply before HS graduation — dual-enrollment only"] },
  { id:"ptk-membership", name:"Phi Theta Kappa Membership (enabler)", sponsor:"Phi Theta Kappa",
    category:"Transfer Flagship", fields:["All"], amount:"~$65–90 (one-time fee)", amountVal:0,
    deadline:{label:"Fall 2026 (get inducted)", iso:"2026-11-01"}, priority:"high", portable:true,
    applyUrl:"https://www.ptk.org/scholarships/faqs/",
    eligibility:"Early-college students with 12+ credits & 3.5 GPA qualify — confirm her CC has a chapter.",
    notes:"The KEY that unlocks the Liberty PTK award, Coca-Cola Academic Team, AND Campbell/App State PTK transfer money.",
    flags:["Confirm CC has an active PTK chapter"] },

  /* ---------- GENERAL MERIT & CHARACTER (national, no major) ---------- */
  { id:"elks-mvs", name:"Elks Most Valuable Student", sponsor:"Elks National Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$1,000–$12,500/yr (top $30k)", amountVal:12500,
    deadline:{label:"Aug 1 – Nov 12, 2026", iso:"2026-11-12"}, priority:"urgent", portable:true,
    applyUrl:"https://www.elks.org/scholars/scholarships/mvs.cfm",
    eligibility:"HS seniors (not grads), US citizens; scholarship + leadership + financial need. Any major.",
    notes:"High-value, portable, clean senior-year fit. Applies through the local Elks lodge → state → national.", flags:[] },
  { id:"dell-scholars", name:"Dell Scholars Program", sponsor:"Michael & Susan Dell Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$20,000 + laptop", amountVal:20000,
    deadline:{label:"~Dec 1, 2026 (verify)", iso:"2026-12-01"}, priority:"high", portable:true,
    applyUrl:"https://www.dellscholars.org/students/",
    eligibility:"GPA 2.4+, Pell-eligible/need, entering a bachelor's. Good odds relative to peers.",
    notes:"BIGGEST GATE: must be in an approved college-readiness program (AVID, GEAR UP, Upward Bound…). Confirm AEC qualifies.",
    flags:["Requires an approved college-readiness program"] },
  { id:"ge-reagan", name:"GE-Reagan Foundation Scholarship", sponsor:"Ronald Reagan Presidential Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$10,000/yr × 4 ($40k)", amountVal:40000,
    deadline:{label:"~Jan 5, 2027", iso:"2027-01-05"}, priority:"high", portable:true,
    applyUrl:"https://www.reaganfoundation.org/education/ge-reagan-foundation-scholarship/",
    eligibility:"HS senior, 3.0+, leadership/drive/integrity/citizenship. Any major.",
    notes:"Bars transfer/continuing students — verify her 4-yr classifies her as a first-time freshman despite the A.A.",
    flags:["Confirm first-time-freshman classification"] },
  { id:"equitable-excellence", name:"Equitable Excellence Scholarship", sponsor:"Equitable Foundation (ex-AXA)",
    category:"General Merit & Character", fields:["All"], amount:"$5,000/yr × 4 (or $2,500)", amountVal:5000,
    deadline:{label:"~Dec 18, 2026", iso:"2026-12-18"}, priority:"high", portable:true,
    applyUrl:"https://scholarshipamerica.org/scholarship/equitableexcellence/",
    eligibility:"HS seniors only, 2.5+ GPA. Essay on courage/strength/wisdom. Any major. 200 awards.",
    notes:"Good fit — apply this senior year; not open to her later as a transfer.", flags:[] },
  { id:"horatio-alger-nc", name:"Horatio Alger NC State Scholarship", sponsor:"Horatio Alger Association",
    category:"General Merit & Character", fields:["All"], amount:"$10,000", amountVal:10000,
    deadline:{label:"~Mar 2027 (senior cycle)", iso:"2027-03-15"}, priority:"high", portable:true,
    applyUrl:"https://scholars.horatioalger.org/scholarships/",
    eligibility:"NC resident, GPA 2.0+, CRITICAL financial need, adversity/perseverance. Any major.",
    notes:"Strong fit (rural + need + character). Note: the NATIONAL award is juniors-only and already missed.",
    flags:["Apply to NC State award, not National"] },
  { id:"taco-bell-livemas", name:"Taco Bell Live Más Scholarship", sponsor:"Taco Bell Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$5,000–$25,000", amountVal:25000,
    deadline:{label:"~Jan 11, 2027", iso:"2027-01-11"}, priority:"high", portable:true,
    applyUrl:"https://www.tacobellfoundation.org/live-mas-scholarship/",
    eligibility:"Ages 16–26, passion/goal VIDEO (no essay), no GPA floor. Any major.",
    notes:"Structurally the best fit — she qualifies as a senior AND could reapply after transferring. Story-driven.", flags:[] },
  { id:"burger-king", name:"Burger King Scholars Program", sponsor:"Burger King Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$1,000–$60,000", amountVal:1000,
    deadline:{label:"~Dec 15, 2026 (or 30k-app cap)", iso:"2026-12-15"}, priority:"high", portable:true,
    applyUrl:"https://burgerking.scholarsapply.org/",
    eligibility:"HS senior, 2.0+ GPA; GPA/work/activities/need/service. Any major.",
    notes:"Apply EARLY — closes at 30,000 applications whichever comes first. Most awards $1,000.", flags:["Caps at 30,000 applications"] },
  { id:"vfw-voice", name:"VFW Voice of Democracy", sponsor:"Veterans of Foreign Wars",
    category:"General Merit & Character", fields:["All"], amount:"$1,000–$35,000", amountVal:35000,
    deadline:{label:"Oct 31, 2026", iso:"2026-10-31"}, priority:"high", portable:true,
    applyUrl:"https://www.vfw.org/community/youth-and-education/youth-scholarships",
    eligibility:"Grades 9–12; a 3–5 min audio-essay on the year's patriotic theme. Any major.",
    notes:"Plays to her essay strength; enter through a local VFW Post. State-level odds are reasonable.", flags:[] },
  { id:"prudential", name:"Prudential Emerging Visionaries", sponsor:"Prudential",
    category:"General Merit & Character", fields:["All"], amount:"$5,000–$15,000", amountVal:15000,
    deadline:{label:"~Nov 2, 2026", iso:"2026-11-02"}, priority:"med", portable:true,
    applyUrl:"https://www.prudential.com/links/about/corporate-social-responsibility/emerging-visionaries",
    eligibility:"Ages 14–18; a community-service or financial-solution project. Any major.",
    notes:"Formerly Spirit of Community — fits her church/civic leadership.", flags:[] },
  { id:"rmhc-scholars", name:"RMHC Scholars Scholarship", sponsor:"Ronald McDonald House Charities",
    category:"General Merit & Character", fields:["All"], amount:"~$1,000+", amountVal:1000,
    deadline:{label:"~Feb 13, 2027", iso:"2027-02-13"}, priority:"med", portable:true,
    applyUrl:"https://www.rmhc.org/rmhc-us-scholarships",
    eligibility:"HS senior, under 21, 2.7+ GPA. Any major. (This is the general award, NOT HACER.)",
    notes:"Must live in a participating RMHC chapter's area — confirm a chapter covers Ashe County.", flags:["Confirm local RMHC chapter participates"] },
  { id:"comcast-leaders", name:"Comcast Leaders & Achievers", sponsor:"Comcast NBCUniversal Foundation",
    category:"General Merit & Character", fields:["All"], amount:"$1,000", amountVal:1000,
    deadline:{label:"~Dec 2026", iso:"2026-12-01"}, priority:"med", portable:true,
    applyUrl:"https://www.accessandequity.org/comcast-leaders-and-achievers-scholarship/",
    eligibility:"HS senior, 2.8+ GPA; principal/counselor NOMINATES. Any major.",
    notes:"Service-area limited — rural Ashe is largely SkyLine/SkyBest, not Comcast. Have the school confirm eligibility.",
    flags:["Likely blocked by Comcast service area"] },

  /* ---------- NO-ESSAY & QUICK APPLY ---------- */
  { id:"bold-bebold", name:"Bold.org \"Be Bold\" + Profile Scholarships", sponsor:"Bold.org",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$25,000 flagship + hundreds more", amountVal:25000,
    deadline:{label:"Rolling (monthly)", iso:""}, priority:"high", portable:true,
    applyUrl:"https://bold.org/scholarships/the-be-bold-no-essay-scholarship/",
    eligibility:"Any student. One free profile auto-matches to female / rural / faith / athlete / undecided awards.",
    notes:"Best single quick-apply pick. Free, real money to the school, replaces the now-defunct Going Merry.", flags:[] },
  { id:"sallie-mae", name:"Sallie Mae $2,000 No-Essay", sponsor:"Sallie Mae",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$2,000", amountVal:2000,
    deadline:{label:"Monthly (last day)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.sallie.com/scholarships/no-essay",
    eligibility:"Monthly drawing. Re-enter each month. (This absorbed the old Nitro College scholarship.)",
    notes:"Legit — paid to the school. Ignore Sallie's loan marketing; exhaust federal aid first.", flags:[] },
  { id:"niche-noessay", name:"Niche $2,000 No-Essay", sponsor:"Niche.com",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$2,000/mo (+$25k–$50k rotating)", amountVal:2000,
    deadline:{label:"Monthly", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.niche.com/colleges/scholarships/no-essay-scholarship/",
    eligibility:"~2-min entry, portable. Random drawing.", notes:"Legit but lead-gen — use a dedicated scholarship email.", flags:[] },
  { id:"appily-easymoney", name:"Appily Easy Money Scholarship", sponsor:"Appily (EAB)",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$1,000", amountVal:1000,
    deadline:{label:"Monthly", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.appily.com/scholarships/easy-money-scholarship",
    eligibility:"Monthly drawing; HS seniors and college students eligible.", notes:"Legit (EAB). 2-min effort; lead-gen.", flags:[] },
  { id:"collegexpress", name:"CollegeXpress Monthly Sweepstakes", sponsor:"CollegeXpress (Carnegie)",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$2,000–$2,500", amountVal:2500,
    deadline:{label:"Monthly", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.collegexpress.com/scholarships/featured/",
    eligibility:"Monthly drawing — confirm the month's rules include HS seniors.", notes:"Legit; free registration is lead-gen.", flags:[] },
  { id:"dosomething", name:"DoSomething \"It Pays to Do Good\"", sponsor:"DoSomething.org",
    category:"No-Essay & Quick Apply", fields:["All"], amount:"$500–$5,000", amountVal:5000,
    deadline:{label:"Rolling (per campaign)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://dosomething.org/us/about/easy-scholarships",
    eligibility:"Ages 13–25; no essay/GPA — join a volunteer campaign, winners by random drawing.",
    notes:"Near-zero effort, low odds. Volume play; also builds a service record.", flags:[] },

  /* ---------- NORTH CAROLINA (state aid + NC-school transfer merit) ---------- */
  { id:"nc-fullride-note", name:"⚠ NC Full-Ride Freshman Scholarships — CLOSED to her", sponsor:"Morehead-Cain, Park, Robertson, Levine, Carswell…",
    category:"North Carolina", fields:["All"], amount:"Full ride (N/A)", amountVal:0,
    deadline:{label:"Not eligible", iso:""}, priority:"med", portable:false,
    applyUrl:"https://moreheadcain.org/application-eligibility/",
    eligibility:"ALL the famous NC full-rides are FIRST-YEAR-FRESHMAN ONLY. With an associate's she enters as a TRANSFER (junior).",
    notes:"Don't spend effort here: Morehead-Cain, Park (NC State), Robertson (UNC/Duke), Levine (UNCC), Wake Carswell, App State Chancellor's, ECU EC Scholars all bar transfers.",
    flags:["Freshman-only — structurally closed to a transfer"] },
  { id:"next-nc", name:"Next NC Scholarship", sponsor:"NCSEAA + UNC System + NCCCS",
    category:"North Carolina", fields:["All"], amount:"CC ≥$3,000/yr · UNC ≥$5,000/yr", amountVal:5000,
    deadline:{label:"Via FAFSA (priority spring 2027)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.cfnc.org/pay-for-college/next-nc-scholarship/",
    eligibility:"AGI ≤ $80k. Transfers qualify (need/enrollment-based). Any major.",
    notes:"Usable only at NC's 58 community colleges + 16 UNC universities. NOT portable to Liberty. Automatic via FAFSA.",
    flags:["NC public schools only"] },
  { id:"golden-leaf", name:"NC Golden LEAF Scholarship", sponsor:"Golden LEAF Foundation",
    category:"North Carolina", fields:["All"], amount:"Up to $14,000 (HS) / $10,500 (transfer)", amountVal:14000,
    deadline:{label:"Mar 1, 2027", iso:"2027-03-01"}, priority:"high", portable:false,
    applyUrl:"https://myportal.ncseaa.edu/",
    eligibility:"Rural county — ASHE CONFIRMED qualifying. GPA 2.5+, SAI ≤ 15,000. Any major.",
    notes:"Biggest rural award, but only at participating NC colleges (incl. App State, ~30 min away). Confirm HS vs transfer track with NCSEAA.",
    flags:["NC participating colleges only; confirm track"] },
  { id:"nc-needbased-private", name:"NC Need-Based Scholarship (Private)", sponsor:"NCSEAA (for NCICU colleges)",
    category:"North Carolina", fields:["All"], amount:"Up to ~$4,600/yr", amountVal:4600,
    deadline:{label:"Via FAFSA", iso:""}, priority:"med", portable:false,
    applyUrl:"https://www.cfnc.org/pay-for-college/",
    eligibility:"Undergrad, no prior bachelor's, SAI ≤ 15,000. Transfers qualify. Any major.",
    notes:"Only at NC private nonprofit (NCICU) colleges — Campbell, Gardner-Webb, Mars Hill, etc. Liberty is not NCICU.",
    flags:["NC private (NCICU) colleges only"] },
  { id:"campbell-scott-ellis", name:"Campbell Scott-Ellis Transfer Scholarship", sponsor:"Campbell University (Christian)",
    category:"North Carolina", fields:["All"], amount:"$11,000–$24,000/yr", amountVal:18000,
    deadline:{label:"Rolling (transfer admission)", iso:""}, priority:"high", portable:false,
    applyUrl:"https://www.campbell.edu/admissions/undergraduate/transfer-student/",
    eligibility:"12+ credits, 2.5+ GPA — AUTOMATIC via admission. Her 3.5+ & full A.A. → upper tiers. Any major.",
    notes:"Best-documented NC win: an automatic transfer award at a Christian university, stackable with NC Need-Based + Golden LEAF + Pell.", flags:[] },
  { id:"gardner-webb-transfer", name:"Gardner-Webb Transfer Merit", sponsor:"Gardner-Webb University (Christian)",
    category:"North Carolina", fields:["All"], amount:"~$5,000–$24,000/yr", amountVal:10000,
    deadline:{label:"Automatic (admission)", iso:""}, priority:"med", portable:false,
    applyUrl:"https://gardner-webb.edu/admissions-aid/transfer-students/",
    eligibility:"Automatic transfer merit in the acceptance letter. Any major.",
    notes:"Transfer tiers not published — call 704-406-4243. Ask about the Tucker (full-ride) & Ignite awards' transfer eligibility.", flags:["Confirm transfer tiers"] },
  { id:"mars-hill-associate", name:"Mars Hill Mountain Lion Associate Scholarship", sponsor:"Mars Hill University (Christian)",
    category:"North Carolina", fields:["All"], amount:"Not published — call", amountVal:8000,
    deadline:{label:"Rolling", iso:""}, priority:"med", portable:false,
    applyUrl:"https://mhu.edu/",
    eligibility:"Built specifically for students who already hold an associate degree. Any major.",
    notes:"The most on-point award for her exact situation, but MHU hides figures — call financial aid. Plus NC Baptist awards fit her faith profile.", flags:["Amounts not published — call"] },
  { id:"ecu-honors-transfer", name:"ECU Honors College Fellows (Transfer)", sponsor:"East Carolina University",
    category:"North Carolina", fields:["All"], amount:"$3,700/yr + Honors", amountVal:3700,
    deadline:{label:"~Mar 19, 2027", iso:"2027-03-19"}, priority:"med", portable:false,
    applyUrl:"https://honors.ecu.edu/transfers/",
    eligibility:"24+ post-HS credits, 3.5+ GPA, last institution = NC community college. Best public transfer fit.",
    notes:"Her profile matches — confirm her Early College A.A. counts as 'last institution = NC CC' (honorscollege@ecu.edu).", flags:[] },
  { id:"appstate-transfer", name:"App State Appalachian Excellence + PTK", sponsor:"Appalachian State University",
    category:"North Carolina", fields:["All"], amount:"$1,000 + $1,000 PTK", amountVal:2000,
    deadline:{label:"~Feb 1, 2027", iso:"2027-02-01"}, priority:"med", portable:false,
    applyUrl:"https://financialaid.appstate.edu/",
    eligibility:"Automatic transfer awards; PTK award needs membership. Any major. ~30 min from Ashe County.",
    notes:"Small but reachable, and App State is close + a Golden LEAF participating school.", flags:[] },
  { id:"ncat-transfer", name:"NC A&T Transfer Scholarships", sponsor:"NC A&T State University",
    category:"North Carolina", fields:["All"], amount:"$1,000/yr", amountVal:1000,
    deadline:{label:"Admit by May 1, 2027", iso:"2027-05-01"}, priority:"med", portable:false,
    applyUrl:"https://www.ncat.edu/",
    eligibility:"3.0+ GPA — near-automatic for transfers. Any major.", notes:"Low-effort, near-automatic.", flags:[] },
  { id:"ncae-mlk", name:"NCAE MLK Jr. Scholarship", sponsor:"NC Association of Educators Foundation",
    category:"North Carolina", fields:["All"], amount:"$2,000", amountVal:2000,
    deadline:{label:"First Monday of Feb 2027", iso:"2027-02-02"}, priority:"high", portable:true,
    applyUrl:"https://www.ncae.org/mlkjrscholarshipinfo",
    eligibility:"NC public HS senior, 2.5+ GPA, essays, need. NOT education-major restricted. 'College of her choice.'",
    notes:"One of the few NC awards that IS portable to Liberty. Confirm Early College counts as 'public HS senior.'", flags:[] },

  /* ---------- HONOR SOCIETIES ---------- */
  { id:"beta", name:"National Beta Scholarship", sponsor:"National Beta Club",
    category:"Honor Society", fields:["All"], amount:"$1,000–$20,000", amountVal:20000,
    deadline:{label:"Opens ~Nov 2026 · due ~Jan 15, 2027", iso:"2027-01-15"}, priority:"urgent", portable:true,
    applyUrl:"https://www.betaclub.org/scholarship-2/",
    eligibility:"Active 12th-grade Senior Beta Member. She IS a Beta member. Any major.",
    notes:"SENIOR-YEAR-ONLY — this fall/winter is her one and only window, ever. Apply at scholarship.betaclub.org.",
    flags:["Senior-year-only — no second chance"] },
  { id:"nhs", name:"NHS Scholarship", sponsor:"National Honor Society (NASSP)",
    category:"Honor Society", fields:["All"], amount:"$3,200–$25,000", amountVal:25000,
    deadline:{label:"Opens Sept 3 · due Nov 20, 2026", iso:"2026-11-20"}, priority:"high", portable:true,
    applyUrl:"https://www.nationalhonorsociety.org/the-nhs-scholarship/",
    eligibility:"Active NHS member (SEPARATE from Beta) verified by chapter adviser. Any major.",
    notes:"Worth more than Beta but only if she's an NHS member too — confirm. Earlier deadline than Beta.",
    flags:["Requires NHS membership (not Beta)"] },
  { id:"mu-alpha-theta", name:"Mu Alpha Theta Scholarship", sponsor:"Mu Alpha Theta",
    category:"Honor Society", fields:["All"], amount:"$4,000–$5,000", amountVal:4000,
    deadline:{label:"~Spring 2027", iso:""}, priority:"med", portable:true,
    applyUrl:"https://mualphatheta.org/scholarships",
    eligibility:"Active member of a math-honor chapter; chapter-nominated. A Two-Year College award also exists.",
    notes:"Only if her Early College has a chapter and she's nominated.", flags:["Chapter-nominated only"] },

  /* ---------- HERITAGE (DAR / SAR) ---------- */
  { id:"dar-america250", name:"DAR America 250! Scholarship", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"$25,000 (10 awards)", amountVal:25000,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"high", portable:true,
    applyUrl:"https://dar.academicworks.com/",
    eligibility:"US citizen, any accredited US college, ANY major. She's a DAR member — a real edge on the story.",
    notes:"The major-agnostic DAR flagship. Some DAR awards want a local-chapter sponsor letter — line that up early.", flags:[] },
  { id:"dar-dunn", name:"DAR Lillian & Arthur Dunn Scholarship", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"$2,500/yr × 4", amountVal:2500,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"high", portable:true,
    applyUrl:"https://dar.academicworks.com/",
    eligibility:"Child of a CURRENT dues-paying DAR member. Both she AND her mother are members — the rare fit. Any major.",
    notes:"Have her mother's National Number ready; confirm mom's dues are active. Only ONE DAR award per cycle.",
    flags:["Confirm mother's DAR dues are current"] },
  { id:"dar-general", name:"DAR National Application (other awards)", sponsor:"Daughters of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"$2,000–$5,000", amountVal:5000,
    deadline:{label:"Nov 1, 2026 – Jan 31, 2027", iso:"2027-01-31"}, priority:"med", portable:true,
    applyUrl:"https://dar.academicworks.com/",
    eligibility:"One online app covers many awards; apply to all she qualifies for.",
    notes:"DAR gives only ONE award per cycle — America 250! and Dunn are her best major-agnostic shots.", flags:["One DAR award per cycle"] },
  { id:"sar-knight", name:"SAR George S. & Stella M. Knight Essay", sponsor:"Sons of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"1st $6,000", amountVal:6000,
    deadline:{label:"~Dec 31, 2026", iso:"2026-12-31"}, priority:"high", portable:true,
    applyUrl:"https://www.sar.org/george-s-stella-m-knight-essay-contest/",
    eligibility:"Any HS student (grades 9–12); 800–1,200 word essay on the Revolution. No membership needed.",
    notes:"Open to her now; enter via the local NC SAR chapter. A contest win — stacks independently of need aid.", flags:[] },
  { id:"sar-rumbaugh", name:"SAR Rumbaugh Oration Contest", sponsor:"Sons of the American Revolution",
    category:"Heritage (DAR/SAR)", fields:["All"], amount:"1st $8,000", amountVal:8000,
    deadline:{label:"Local/state vary (fall–winter)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.sar.org/joseph-s-rumbaugh-historical-oration-contest/",
    eligibility:"Any student grades 9–12; 5–6 min memorized oration on the Revolution.",
    notes:"Open to her now; contact the local NC SAR chapter for deadlines.", flags:[] },

  /* ---------- FAITH-BASED ---------- */
  { id:"provision-bullard", name:"Bullard Family Scholarship (ministry)", sponsor:"NC Baptist Foundation / Provision",
    category:"Faith-Based", fields:["All"], amount:"$500–$2,500/yr", amountVal:2500,
    deadline:{label:"~May 1, 2027 (opens Jan 1)", iso:"2027-05-01"}, priority:"med", portable:true,
    applyUrl:"https://www.provision.org/scholarships",
    eligibility:"NC resident, Baptist State Convention of NC church member, committed to full-time Christian ministry.",
    notes:"Best fit if a ministry path emerges. Only ONE Provision award per cycle.", flags:["One Provision award per cycle"] },
  { id:"provision-general", name:"Martha Watson / Nell J. Clary Scholarship", sponsor:"NC Baptist Foundation / Provision",
    category:"Faith-Based", fields:["All"], amount:"$500–$2,500/yr", amountVal:2500,
    deadline:{label:"~May 1, 2027", iso:"2027-05-01"}, priority:"med", portable:true,
    applyUrl:"https://www.provision.org/scholarships",
    eligibility:"NC resident, BSCNC church member; general students. Fits 3.5 GPA + church leadership. Any major.",
    notes:"The general (non-ministry) Provision option — but only one Provision award per cycle.", flags:["One Provision award per cycle"] },
  { id:"christian-connector", name:"Christian Connector Scholarship Drawings", sponsor:"The Christian Connector",
    category:"Faith-Based", fields:["All"], amount:"$2,000–$5,000", amountVal:5000,
    deadline:{label:"Annual — watch for reopen", iso:""}, priority:"med", portable:true,
    applyUrl:"http://christianconnector.com/",
    eligibility:"No-essay drawing; enrolling at a Christ-centered college.", notes:"Monitor for the next cycle. Verify the 'first-time full-time' rule.", flags:["Verify transfer eligibility"] },
  { id:"bold-christian", name:"Bold.org Christian Scholarships", sponsor:"Bold.org",
    category:"Faith-Based", fields:["All"], amount:"Varies (60+ awards)", amountVal:1000,
    deadline:{label:"Rolling (monthly)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://bold.org/scholarships/by-type/christian-scholarships/",
    eligibility:"Christian students; character/faith framing. Any major.", notes:"Covered by the same free Bold.org profile.", flags:[] },
  { id:"fca", name:"FCA Scholarships", sponsor:"Fellowship of Christian Athletes",
    category:"Faith-Based", fields:["All"], amount:"Varies", amountVal:1000,
    deadline:{label:"~May (varies by chapter)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.carolinasfca.org/",
    eligibility:"Active FCA huddle member; decentralized by chapter.", notes:"Ask the Carolinas/NC FCA rep about college awards.", flags:["Requires active FCA involvement"] },

  /* ---------- SCHOLAR-ATHLETE ---------- */
  { id:"foot-locker", name:"Foot Locker Scholar Athletes", sponsor:"Foot Locker Foundation",
    category:"Scholar-Athlete", fields:["All"], amount:"$20,000 ($5k/yr × 4)", amountVal:20000,
    deadline:{label:"~Jan 9, 2027 (opens ~Dec)", iso:"2027-01-09"}, priority:"high", portable:true,
    applyUrl:"https://www.footlockerscholarathletes.com/",
    eligibility:"HS senior on a sports team (swimming counts!), GPA 3.0+, entering a 4-yr. 500-word leadership essay. Any major.",
    notes:"Best athlete fit — $20k, portable. Same dual-enrollment gray area as GE-Reagan: confirm her A.A. doesn't void 'first-time freshman' status.",
    flags:["Confirm first-time-freshman status"] },
  { id:"nchsaa-scholar", name:"NCHSAA Foundation Scholar Award", sponsor:"NC High School Athletic Assn. Foundation",
    category:"Scholar-Athlete", fields:["All"], amount:"$2,500", amountVal:2500,
    deadline:{label:"~Spring 2027 (via school AD)", iso:"2027-03-15"}, priority:"high", portable:true,
    applyUrl:"https://nchsaafoundation.org/scholarships/",
    eligibility:"NC varsity student-athlete; leadership + financial need. Not swim-specific. Any major.",
    notes:"Strong NC fit. Confirm Ashe Early College is an NCHSAA member and swim is a sanctioned varsity team; get the deadline from her AD.",
    flags:["Confirm AEC is an NCHSAA member school"] },
  { id:"wsf-riddle", name:"WSF Linda Riddle / SGMA Scholarship", sponsor:"Women's Sports Foundation",
    category:"Scholar-Athlete", fields:["All"], amount:"$1,500", amountVal:1500,
    deadline:{label:"~Spring 2027 (verify)", iso:"2027-03-01"}, priority:"med", portable:true,
    applyUrl:"https://www.womenssportsfoundation.org/wsf_programs/linda-riddle-sgma-endowed-scholarship/",
    eligibility:"HS female athlete, 3.5+ GPA, financial need, first-year student. Any major.",
    notes:"Female + 3.5 GPA + need all match her cleanly. Small but a high-probability fit.", flags:[] },
  { id:"nisca-aaa", name:"NISCA Academic All-America (credential)", sponsor:"Nat'l Interscholastic Swim Coaches Assn.",
    category:"Scholar-Athlete", fields:["All"], amount:"Recognition (no cash)", amountVal:0,
    deadline:{label:"Portal opens Jan 1, 2027", iso:"2027-01-15"}, priority:"med", portable:true,
    applyUrl:"https://www.niscaonline.org/",
    eligibility:"HS senior swimmer, varsity letter, 3.75 senior-year GPA. Coach submits.",
    notes:"Not money — a national honor. Pursue it as a résumé line that strengthens her cash applications (if she can hit 3.75 senior year).",
    flags:["Recognition only; needs 3.75 GPA"] },
  { id:"cbsmf", name:"Charles B. Staats Memorial (swim)", sponsor:"CBSMF",
    category:"Scholar-Athlete", fields:["All"], amount:"$3,500/yr renewable", amountVal:3500,
    deadline:{label:"~Spring 2027 (verify)", iso:"2027-04-01"}, priority:"med", portable:true,
    applyUrl:"https://www.cbsmf.org/scholarship.html",
    eligibility:"HS senior swimmer, 3.0+ GPA — BUT requires 2+ yrs as a youth swim COACH, continuing the summer after graduation.",
    notes:"Only viable if she takes a summer-league/YMCA coaching role. If she does, it's a renewable $3,500/yr — worth it.",
    flags:["Requires a youth swim-coaching role"] },

  /* ---------- WOMEN IN LEADERSHIP ---------- */
  { id:"peo-star", name:"P.E.O. STAR Scholarship", sponsor:"P.E.O. International",
    category:"Women in Leadership", fields:["All"], amount:"$2,500", amountVal:2500,
    deadline:{label:"~Feb–Mar 2027 (chapter submits)", iso:"2027-03-01"}, priority:"high", portable:true,
    applyUrl:"https://www.peointernational.org/educational-support/star-scholarship/",
    eligibility:"Women in final year of HS; leadership/academics/service. Any major.",
    notes:"Requires sponsorship by a local P.E.O. chapter — identify and contact a nearby chapter NOW.", flags:["Needs a local P.E.O. chapter sponsor"] },
  { id:"zonta-ywpa", name:"Zonta Young Women in Public Affairs", sponsor:"Zonta International",
    category:"Women in Leadership", fields:["All"], amount:"$5,000", amountVal:5000,
    deadline:{label:"Local-club deadline (spring 2027)", iso:"2027-03-01"}, priority:"med", portable:true,
    applyUrl:"https://www.zonta.org/",
    eligibility:"Women ages 16–19; leadership + civic/public service. Any major.",
    notes:"Apply through a local Zonta club — not all areas have one; check for a nearby club.", flags:["Needs a local Zonta club"] },
  { id:"gfwc-local", name:"GFWC Women's-Club Scholarships", sponsor:"General Federation of Women's Clubs",
    category:"Women in Leadership", fields:["All"], amount:"~$1,000–$1,500", amountVal:1500,
    deadline:{label:"Varies (spring)", iso:""}, priority:"med", portable:true,
    applyUrl:"https://www.gfwc.org/",
    eligibility:"HS senior women; criteria vary by club. Any major.",
    notes:"The real money is at the LOCAL woman's-club level — contact the nearest NC GFWC club.", flags:["Contact the local club"] },
  { id:"gloria-barron", name:"Gloria Barron Prize for Young Heroes", sponsor:"Barron Prize",
    category:"General Merit & Character", fields:["All"], amount:"$10,000", amountVal:10000,
    deadline:{label:"~Apr 15, 2027", iso:"2027-04-15"}, priority:"med", portable:true,
    applyUrl:"https://barronprize.org/apply/",
    eligibility:"Ages 8–18 who led a significant public-service project. Any major.",
    notes:"A fit only if she has led a concrete service project (church/community).", flags:[] },

  /* ---------- CIVIC & LOCAL ---------- */
  { id:"nccf-universal", name:"NC Community Foundation Universal App", sponsor:"NC Community Foundation / Ashe County CF",
    category:"Civic & Local", fields:["All"], amount:"Varies (Beaver Creek ~$6,000)", amountVal:6000,
    deadline:{label:"~Mid-Dec 2026 – early Mar 2027", iso:"2027-03-03"}, priority:"high", portable:true,
    applyUrl:"https://www.nccommunityfoundation.org/scholarships/how-to-apply",
    eligibility:"ONE portable application matches her to 130+ funds statewide, incl. 6+ Ashe County funds. Any US school (Liberty OK).",
    notes:"Highest-ROI cluster and it IS portable to Liberty. Confirm 2027 dates in Dec 2026.", flags:["Skip Ronald Keith Vannoy (2-yr only)"] },
  { id:"ashe-chamber", name:"Ashe County Chamber Scholarship (Ashe Advantage)", sponsor:"Ashe County Chamber of Commerce",
    category:"Civic & Local", fields:["All"], amount:"~$1,000–$1,500 (17 awards in 2025)", amountVal:1500,
    deadline:{label:"~Late March 2027", iso:"2027-03-28"}, priority:"high", portable:true,
    applyUrl:"https://ashechamber.com/scholarships.php",
    eligibility:"ACHS / Ashe Early College / homeschool seniors; 2.75+ GPA; any accredited college. Any major.",
    notes:"Best-fit local award — high acceptance volume, rural-community priority. Needs resume, transcript, essay, interview.", flags:[] },
  { id:"counselor-list", name:"ACHS/AEC Guidance Office Scholarship List", sponsor:"Ashe HS / Early College guidance office",
    category:"Civic & Local", fields:["All"], amount:"Varies (many $500–$1,000 local)", amountVal:1000,
    deadline:{label:"Senior year (ask now)", iso:"2026-09-15"}, priority:"high", portable:true,
    applyUrl:"https://www.ashe.k12.nc.us/",
    eligibility:"Many local church/civic scholarships (Farm Bureau, Sertoma, Masonic, 3× ACHS $1,000) publish ONLY in the counselor's packet.",
    notes:"Request the master senior scholarship list from her counselor — the authoritative source for local money.", flags:["Not online — get the printed/Classroom list"] },
  { id:"skyline", name:"Frank James – SkyLine Scholarship", sponsor:"SkyLine/SkyBest",
    category:"Civic & Local", fields:["All"], amount:"$1,000/yr renewable × 4", amountVal:1000,
    deadline:{label:"~Spring 2027", iso:"2027-03-15"}, priority:"med", portable:true,
    applyUrl:"https://www.skybest.com/about-us/community/frank-james-skyline-scholarship-application",
    eligibility:"Parent must be a SkyLine/SkyBest customer ≥1 yr (Ashe/Alleghany/Avery/Watauga). Any major.",
    notes:"Only if the family has SkyLine/SkyBest service. Renewable — worth it if eligible.", flags:["Requires SkyLine/SkyBest service"] },
  { id:"dr-pepper", name:"Dr Pepper Tuition Giveaway", sponsor:"Keurig Dr Pepper",
    category:"Civic & Local", fields:["All"], amount:"Up to $100,000", amountVal:100000,
    deadline:{label:"Opens ~Aug · due Sept 30, 2026", iso:"2026-09-30"}, priority:"med", portable:true,
    applyUrl:"https://www.drpepper.com/tuition/",
    eligibility:"Ages 18–24; a 60-second video on your goals. No major or GPA requirement. Transfer-friendly.",
    notes:"Big upside, low barrier. A fun one to enter.", flags:[] },
  { id:"american-legion", name:"American Legion / Auxiliary Scholarships", sponsor:"American Legion (NC Dept.)",
    category:"Civic & Local", fields:["All"], amount:"Varies", amountVal:2000,
    deadline:{label:"~Spring 2027", iso:"2027-03-01"}, priority:"med", portable:true,
    applyUrl:"https://www.legion.org/scholarships",
    eligibility:"Several awards; some favor descendants of veterans. Any major.", notes:"Check the NC Department's specific awards.", flags:[] },
  { id:"dollars-for-scholars", name:"Scholarship America Dream Award", sponsor:"Scholarship America",
    category:"Civic & Local", fields:["All"], amount:"$5,000–$15,000 renewable", amountVal:10000,
    deadline:{label:"~Oct–Nov 2026", iso:"2026-11-01"}, priority:"med", portable:true,
    applyUrl:"https://scholarshipamerica.org/students/dream-award/",
    eligibility:"For students who've completed ≥1 year of post-secondary — an A.A. transfer is a strong fit. Any major.",
    notes:"No local Ashe Dollars-for-Scholars chapter exists, but the national Dream Award fits her transfer profile.", flags:[] }

];
